create table if not exists public.listings (
  id bigint generated by default as identity primary key,
  dedupe_key text not null unique,
  county text not null,
  license_type text not null check (license_type in ('4COP Quota', '3PS Quota / Package Store')),
  price integer,
  price_label text not null,
  source_ref text,
  source_name text,
  source_url text,
  note text,
  image text not null,
  status text not null default 'available' check (status in ('available', 'sold')),
  inventory_class text not null default 'market' check (inventory_class in ('market', 'direct_seller', 'fllm_exclusive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create index if not exists listings_status_idx on public.listings(status);
create index if not exists listings_county_idx on public.listings(county);
create index if not exists listings_source_url_idx on public.listings(source_url) where source_url is not null;
create index if not exists listings_source_ref_idx on public.listings(source_ref) where source_ref is not null;
create index if not exists listings_last_seen_idx on public.listings(last_seen_at);
create index if not exists listings_inventory_class_idx on public.listings(inventory_class);

alter table public.listings enable row level security;

-- The website reads and writes through the server using SUPABASE_SERVICE_ROLE_KEY.
-- No public browser policy is required.
