import type { ListingWithInventoryClass } from "@/lib/listing-inventory-class";

export type QuotaOfferClassification =
  | "standalone_quota"
  | "business_package"
  | "dual_offering"
  | "excluded";

export type QuotaOfferFacts = {
  isTransferableQuotaLicense: boolean;
  includesOperatingBusiness: boolean;
  licenseAvailableSeparately: boolean;
};

export const FLLM_QUOTA_LISTING_OPERATING_RULES = [
  {
    classification: "standalone_quota",
    label: "Standalone Quota License",
    placement: "Standalone license inventory",
    description:
      "A separately purchasable 4COP or 3PS quota license belongs only in FLLM's standalone inventory and market statistics.",
  },
  {
    classification: "business_package",
    label: "Business + Quota License",
    placement: "Business-package inventory",
    description:
      "An operating business sold with an included quota license belongs only in Businesses With Quota Licenses and is excluded from standalone statistics.",
  },
  {
    classification: "dual_offering",
    label: "Separately Authorized Offers",
    placement: "Two distinct listings",
    description:
      "When a broker expressly offers the business package and the license separately, FLLM creates distinct records, prices, disclosures, and search intent for each offer.",
  },
  {
    classification: "excluded",
    label: "Nonquota or Premises-Dependent License",
    placement: "Excluded from quota inventory",
    description:
      "A business involving only a nonquota, specialty, or premises-dependent license is not published as FLLM quota-license inventory.",
  },
] as const satisfies ReadonlyArray<{
  classification: QuotaOfferClassification;
  label: string;
  placement: string;
  description: string;
}>;

export function classifyQuotaOffer({
  isTransferableQuotaLicense,
  includesOperatingBusiness,
  licenseAvailableSeparately,
}: QuotaOfferFacts): QuotaOfferClassification {
  if (!isTransferableQuotaLicense) return "excluded";
  if (includesOperatingBusiness && licenseAvailableSeparately) return "dual_offering";
  if (includesOperatingBusiness) return "business_package";
  return "standalone_quota";
}

export type BusinessQuotaCategory =
  | "Bar"
  | "Cocktail Lounge"
  | "Nightclub"
  | "Restaurant"
  | "Bowling Alley"
  | "Liquor Store"
  | "Marina"
  | "Gentlemen's Club"
  | "Hotel / Motel"
  | "Country Club"
  | "Other Hospitality";

export type BusinessQuotaListing = {
  listingReference: string;
  inventoryReferences?: readonly string[];
  href: string;
  county: string;
  countyHref: string;
  licenseType: "4COP Quota" | "3PS Quota / Package Store" | "4COP SFS/SRX" | "2COP Beer & Wine";
  licenseClass: "quota" | "sfs" | "2cop";
  title: string;
  businessType: string;
  businessCategory: BusinessQuotaCategory;
  summaryBusinessType: string;
  transactionType: string;
  packagePrice: string;
  packagePriceNumber: number;
  allocatedLicenseValue: string;
  brokerName: string;
  brokerage: string;
  featured: boolean;
  listingTier?: "featured" | "market";
  marketViewHref?: string;
  publicationStatus: "published" | "preview";
  classification: "business_package" | "business_sfs" | "business_2cop";
  sellerDirect?: boolean;
};

/**
 * Canonical registry for third-party broker offerings that include an
 * operating business and a quota license. These records are deliberately
 * separate from statewide standalone-license inventory, pricing statistics,
 * county counts, market comparisons, and the Exchange.
 *
 * Preview records remain classified here so they cannot leak into standalone
 * inventory, but they are not exposed on the public business inventory until
 * the broker listing is approved and publicationStatus becomes "published".
 */
export const businessQuotaListingRecords: BusinessQuotaListing[] = [
  {
    listingReference: "FLLM-ANTEZZA",
    href: "/listings/fllm-antezza",
    county: "Pinellas County",
    countyHref: "/counties/pinellas",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Pinellas County Cocktail Lounge + 4COP Quota License",
    businessType: "Upscale cocktail lounge",
    businessCategory: "Cocktail Lounge",
    summaryBusinessType: "Cocktail Lounge",
    transactionType: "Asset Sale",
    packagePrice: "$999,000",
    packagePriceNumber: 999_000,
    allocatedLicenseValue: "$460,000",
    brokerName: "Alessandro Antezza",
    brokerage: "SUNSHINEAGLE LLC",
    featured: true,
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-DESAMOURS",
    href: "/listings/fllm-desamours",
    county: "Martin County",
    countyHref: "/counties/martin",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Iconic Jensen Beach Bar + 4COP Quota License",
    businessType: "Long-established neighborhood bar",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Asset Sale",
    packagePrice: "$650,000",
    packagePriceNumber: 650_000,
    allocatedLicenseValue: "$600,000 est.",
    brokerName: "JR DesAmours",
    brokerage: "Business Exit Advisors",
    featured: true,
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-NEGOVAN",
    href: "/listings/fllm-negovan",
    county: "Miami-Dade County",
    countyHref: "/counties/miami-dade",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Miami Adult Nightclub + 4COP Quota License",
    businessType: "Premium adult-entertainment business",
    businessCategory: "Gentlemen's Club",
    summaryBusinessType: "Gentlemen's Club",
    transactionType: "Business Package",
    packagePrice: "$3,500,000",
    packagePriceNumber: 3_500_000,
    allocatedLicenseValue: "$250,000",
    brokerName: "Julie Negovan",
    brokerage: "Patricia Burnside Realty",
    featured: true,
    publicationStatus: "preview",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MELLO",
    inventoryReferences: ["FLLM-265072"],
    href: "/listings/fllm-mello",
    county: "Palm Beach County",
    countyHref: "/counties/palm-beach",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Delray Beach Restaurant + 4COP Quota License",
    businessType: "Turnkey full-service restaurant and bar",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Asset Sale",
    packagePrice: "$359,000",
    packagePriceNumber: 359_000,
    allocatedLicenseValue: "$200,000",
    brokerName: "Leonard Mello",
    brokerage: "We Sell Restaurants",
    featured: true,
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-ZOBERG",
    href: "/listings/fllm-zoberg",
    county: "Miami-Dade County",
    countyHref: "/counties/miami-dade",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Miami-Dade Mexican Restaurant + 4COP SFS / SRX License",
    businessType: "Mexican-Latin restaurant and entertainment venue",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$1,200,000",
    packagePriceNumber: 1_200_000,
    allocatedLicenseValue: "Location-specific",
    brokerName: "Brian Zoberg",
    brokerage: "Suncoast Business Consultants",
    featured: true,
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-KOPP",
    href: "/listings/fllm-kopp",
    county: "Miami-Dade County",
    countyHref: "/counties/miami-dade",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Miami Peruvian Restaurant + 2COP Beer & Wine License",
    businessType: "Peruvian-Mediterranean restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$599,999",
    packagePriceNumber: 599_999,
    allocatedLicenseValue: "No separate quota value",
    brokerName: "Marianella Kopp",
    brokerage: "Seller Direct",
    sellerDirect: true,
    featured: true,
    publicationStatus: "preview",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-Q-001",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Martin County",
    countyHref: "/counties/martin",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Martin County Pub + 4COP Quota License",
    businessType: "Pub and bar",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$795,000",
    packagePriceNumber: 795_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-002",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Sarasota County",
    countyHref: "/counties/sarasota",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Sarasota County Bar + 4COP Quota License",
    businessType: "Bar and lounge",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$756,000",
    packagePriceNumber: 756_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-003",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "St. Lucie County",
    countyHref: "/counties/st-lucie",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "St. Lucie County Bar + 4COP Quota License",
    businessType: "Bar",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$420,000",
    packagePriceNumber: 420_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-004",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "St. Johns County",
    countyHref: "/counties/st-johns",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "St. Augustine Bar / Restaurant + 4COP Quota License",
    businessType: "Sports bar and restaurant",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$999,000",
    packagePriceNumber: 999_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-SFS-001",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Broward County Full-Service Restaurant + 4COP SFS/SRX",
    businessType: "Full-service restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Asset Sale",
    packagePrice: "$499,000",
    packagePriceNumber: 499_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-002",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Fort Lauderdale Italian Restaurant + 4COP SFS",
    businessType: "Italian restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$400,000",
    packagePriceNumber: 400_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-003",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Orange County",
    countyHref: "/counties/orange",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Orlando Restaurant + 4COP SFS",
    businessType: "Full-service restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$250,000",
    packagePriceNumber: 250_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-004",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Seminole County",
    countyHref: "/counties/seminole",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Seminole County Restaurant + 4COP SFS",
    businessType: "Full-service restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$150,000",
    packagePriceNumber: 150_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-2COP-001",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Orange County",
    countyHref: "/counties/orange",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Orlando Restaurant + 2COP Beer & Wine",
    businessType: "Franchise restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$275,000",
    packagePriceNumber: 275_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-002",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Manatee County",
    countyHref: "/counties/manatee",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Lakewood Ranch Restaurant + 2COP Beer & Wine",
    businessType: "Restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$135,000",
    packagePriceNumber: 135_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-003",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Hillsborough County",
    countyHref: "/counties/hillsborough",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Hillsborough County Restaurant + 2COP Beer & Wine",
    businessType: "Breakfast and lunch restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$199,999",
    packagePriceNumber: 199_999,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-004",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Brevard County",
    countyHref: "/counties/brevard",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Brevard County Restaurant + 2COP Beer & Wine",
    businessType: "Italian restaurant and wine bar",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$315,000",
    packagePriceNumber: 315_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-005",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Miami-Dade County",
    countyHref: "/counties/miami-dade",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Downtown Miami Restaurant + 2COP Beer & Wine",
    businessType: "Turnkey restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$195,000",
    packagePriceNumber: 195_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },

  {
    listingReference: "FLLM-MKT-Q-005",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Duval County",
    countyHref: "/counties/duval",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Jacksonville Bar + 4COP Quota License",
    businessType: "High-capacity bar and restaurant",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$950,000",
    packagePriceNumber: 950_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-006",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Duval County",
    countyHref: "/counties/duval",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Atlantic Beach Bar + Real Estate + 4COP Quota License",
    businessType: "Neighborhood bar with real estate",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business + Real Estate Sale",
    packagePrice: "$2,650,000",
    packagePriceNumber: 2_650_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-007",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Hillsborough County",
    countyHref: "/counties/hillsborough",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Tampa Bay Sports Bar + 4COP Quota License",
    businessType: "Sports bar and grill",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$549,900",
    packagePriceNumber: 549_900,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-008",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "3PS Quota / Package Store",
    licenseClass: "quota",
    title: "Broward County Liquor Store + 3PS Quota License",
    businessType: "Retail liquor store",
    businessCategory: "Liquor Store",
    summaryBusinessType: "Liquor Store",
    transactionType: "Business Sale",
    packagePrice: "$435,000",
    packagePriceNumber: 435_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-009",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Miami-Dade County",
    countyHref: "/counties/miami-dade",
    licenseType: "3PS Quota / Package Store",
    licenseClass: "quota",
    title: "Miami Liquor Store + 3PS Quota License",
    businessType: "Established retail liquor store",
    businessCategory: "Liquor Store",
    summaryBusinessType: "Liquor Store",
    transactionType: "Business Sale",
    packagePrice: "$420,000",
    packagePriceNumber: 420_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-SFS-005",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Brevard County",
    countyHref: "/counties/brevard",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Brevard County Restaurant + 4COP SFS/SRX License",
    businessType: "Restaurant and bar",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Asset Sale",
    packagePrice: "$799,000",
    packagePriceNumber: 799_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-006",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Oakland Park Restaurant + Bar + 4COP SFS/SRX",
    businessType: "Restaurant and bar",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Asset Sale",
    packagePrice: "$450,000",
    packagePriceNumber: 450_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-007",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Pinellas County",
    countyHref: "/counties/pinellas",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Clearwater Sports Bar + 4COP SFS/SRX License",
    businessType: "High-volume sports bar and restaurant",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$950,000",
    packagePriceNumber: 950_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-008",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Sarasota County",
    countyHref: "/counties/sarasota",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Downtown Sarasota Restaurant + 4COP SFS/SRX",
    businessType: "Restaurant and full bar",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Asset Sale",
    packagePrice: "$215,000",
    packagePriceNumber: 215_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-009",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Miramar Entertainment Venue + Restaurant + 4COP SFS/SRX",
    businessType: "Restaurant and entertainment venue",
    businessCategory: "Other Hospitality",
    summaryBusinessType: "Entertainment Venue",
    transactionType: "Business Sale",
    packagePrice: "$75,000",
    packagePriceNumber: 75_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-2COP-006",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Palm Beach County",
    countyHref: "/counties/palm-beach",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Palm Beach County Breakfast & Lunch Restaurant + 2COP",
    businessType: "Breakfast and lunch restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$220,000",
    packagePriceNumber: 220_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-007",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Osceola County",
    countyHref: "/counties/osceola",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "St. Cloud Restaurant + Bar + 2COP Beer & Wine",
    businessType: "Restaurant and bar",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$159,999",
    packagePriceNumber: 159_999,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-008",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Miami-Dade County",
    countyHref: "/counties/miami-dade",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Miami-Dade Cafe & Bakery + 2COP Beer & Wine",
    businessType: "Cafe, bakery and restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$599,000",
    packagePriceNumber: 599_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-Q-010",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Pinellas County",
    countyHref: "/counties/pinellas",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Downtown Pinellas County Bar + 4COP Quota License",
    businessType: "Downtown bar",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$1,050,000",
    packagePriceNumber: 1_050_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-SFS-010",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Fort Lauderdale Beach Restaurant + 4COP SFS/SRX",
    businessType: "Beachfront full-service restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$350,000",
    packagePriceNumber: 350_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-011",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Pasco County",
    countyHref: "/counties/pasco",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Pasco County Italian Restaurant + 4COP SFS/SRX",
    businessType: "Italian restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$519,000",
    packagePriceNumber: 519_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-012",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Pompano Beach Restaurant + 4COP SFS/SRX",
    businessType: "Full-service restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$249,000",
    packagePriceNumber: 249_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-013",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "East Fort Lauderdale Italian Restaurant + 4COP SFS/SRX",
    businessType: "Italian restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$400,000",
    packagePriceNumber: 400_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-014",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Palm Beach County",
    countyHref: "/counties/palm-beach",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Lake Worth Tavern + 4COP SFS/SRX",
    businessType: "Neighborhood tavern and grill",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$199,000",
    packagePriceNumber: 199_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-015",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Sarasota County",
    countyHref: "/counties/sarasota",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Sarasota Restaurant + Real Estate + 4COP SFS/SRX",
    businessType: "Established restaurant with real estate",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business + Real Estate Sale",
    packagePrice: "$1,549,000",
    packagePriceNumber: 1_549_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-2COP-009",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Sarasota County",
    countyHref: "/counties/sarasota",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Sarasota Pub + 2COP Beer & Wine",
    businessType: "Long-established pub and restaurant",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$475,000",
    packagePriceNumber: 475_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-010",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Charlotte County",
    countyHref: "/counties/charlotte",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Punta Gorda Sushi Restaurant + 2COP Beer & Wine",
    businessType: "Sushi restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Asset Sale",
    packagePrice: "$110,000",
    packagePriceNumber: 110_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-011",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Manatee County",
    countyHref: "/counties/manatee",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Manatee County Wine Store & Wine Bar + 2COP",
    businessType: "Retail wine store and wine bar",
    businessCategory: "Liquor Store",
    summaryBusinessType: "Wine Store & Bar",
    transactionType: "Business Sale",
    packagePrice: "$399,999",
    packagePriceNumber: 399_999,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-012",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Broward County Cuban Restaurant + 2COP Beer & Wine",
    businessType: "Cuban restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$99,000",
    packagePriceNumber: 99_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-013",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "St. Lucie County",
    countyHref: "/counties/st-lucie",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "St. Lucie County Breakfast & Lunch Cafe + 2COP",
    businessType: "Breakfast and lunch cafe",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$375,000",
    packagePriceNumber: 375_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-014",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Palm Beach County",
    countyHref: "/counties/palm-beach",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Boynton Beach BBQ Restaurant + 2COP Beer & Wine",
    businessType: "BBQ restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$99,000",
    packagePriceNumber: 99_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-015",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Pinellas County",
    countyHref: "/counties/pinellas",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Pinellas County Dog Bar & Social Venue + 2COP",
    businessType: "Dog-friendly bar and entertainment venue",
    businessCategory: "Other Hospitality",
    summaryBusinessType: "Entertainment Venue",
    transactionType: "Asset Sale",
    packagePrice: "$275,000",
    packagePriceNumber: 275_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-Q-011",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Polk County",
    countyHref: "/counties/polk",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Polk County Tavern & BBQ Restaurant + 4COP Quota License",
    businessType: "Tavern and BBQ restaurant",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$1,000,000",
    packagePriceNumber: 1_000_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-012",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Sarasota County",
    countyHref: "/counties/sarasota",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Sarasota Bar + Real Estate + 4COP Quota License",
    businessType: "Bar with real estate",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business + Real Estate Sale",
    packagePrice: "$2,299,000",
    packagePriceNumber: 2_299_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-013",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Hillsborough County",
    countyHref: "/counties/hillsborough",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Tampa Cigar Bar / Lounge + 4COP Quota License",
    businessType: "Cigar and hookah lounge",
    businessCategory: "Cocktail Lounge",
    summaryBusinessType: "Cocktail Lounge",
    transactionType: "Asset Sale",
    packagePrice: "$310,000",
    packagePriceNumber: 310_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-014",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Broward County Nightclub + 4COP Quota License",
    businessType: "Established nightclub",
    businessCategory: "Nightclub",
    summaryBusinessType: "Nightclub",
    transactionType: "Business Sale",
    packagePrice: "$495,000",
    packagePriceNumber: 495_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-015",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Downtown Hollywood Nightclub + 4COP Quota License",
    businessType: "Nightclub, bar and lounge",
    businessCategory: "Nightclub",
    summaryBusinessType: "Nightclub",
    transactionType: "Business Sale",
    packagePrice: "$790,000",
    packagePriceNumber: 790_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-016",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Volusia County",
    countyHref: "/counties/volusia",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Daytona Beach Adult Nightclub + Real Estate + 4COP Quota",
    businessType: "Adult nightclub with real estate",
    businessCategory: "Gentlemen's Club",
    summaryBusinessType: "Gentlemen's Club",
    transactionType: "Business + Real Estate Sale",
    packagePrice: "$2,300,000",
    packagePriceNumber: 2_300_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-017",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Orange County",
    countyHref: "/counties/orange",
    licenseType: "3PS Quota / Package Store",
    licenseClass: "quota",
    title: "Orange County Liquor Store + 3PS Quota License",
    businessType: "Retail liquor store",
    businessCategory: "Liquor Store",
    summaryBusinessType: "Liquor Store",
    transactionType: "Business Sale",
    packagePrice: "$795,000",
    packagePriceNumber: 795_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-SFS-016",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Pinellas County",
    countyHref: "/counties/pinellas",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "St. Pete Beach Waterfront Restaurant + 4COP SFS/SRX",
    businessType: "Waterfront restaurant and bar",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$1,200,000",
    packagePriceNumber: 1_200_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-2COP-016",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Lake County",
    countyHref: "/counties/lake",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Mount Dora Cafe & Eatery + 2COP Beer & Wine",
    businessType: "Cafe and restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Asset Sale",
    packagePrice: "$360,000",
    packagePriceNumber: 360_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-Q-018",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Broward Beachside Restaurant & Nightclub + 4COP Quota",
    businessType: "Beachside restaurant and nightclub",
    businessCategory: "Nightclub",
    summaryBusinessType: "Nightclub",
    transactionType: "Business Sale",
    packagePrice: "$1,650,000",
    packagePriceNumber: 1_650_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-019",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Brevard County",
    countyHref: "/counties/brevard",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Palm Bay Adult Nightclub + Real Estate + 4COP Quota",
    businessType: "Adult nightclub with real estate",
    businessCategory: "Gentlemen's Club",
    summaryBusinessType: "Gentlemen's Club",
    transactionType: "Business + Real Estate Sale",
    packagePrice: "$2,300,000",
    packagePriceNumber: 2_300_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-020",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Miami-Dade County",
    countyHref: "/counties/miami-dade",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Miami Beach Nightclub & Cabaret + 4COP Full Liquor License",
    businessType: "Nightclub and cabaret",
    businessCategory: "Nightclub",
    summaryBusinessType: "Nightclub",
    transactionType: "Business Sale",
    packagePrice: "$750,000",
    packagePriceNumber: 750_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-SFS-017",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Palm Beach County",
    countyHref: "/counties/palm-beach",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Boca Raton Latin-Fusion Restaurant + 4COP SFS/SRX",
    businessType: "Latin-fusion restaurant and entertainment venue",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$495,000",
    packagePriceNumber: 495_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-018",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Hollywood Restaurant & Bar + 4COP SFS/SRX",
    businessType: "Restaurant and bar with outdoor seating",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$499,000",
    packagePriceNumber: 499_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-019",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Pinellas County",
    countyHref: "/counties/pinellas",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Largo Landmark Restaurant + 4COP SFS/SRX",
    businessType: "Established full-service restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$995,000",
    packagePriceNumber: 995_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-2COP-017",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Hernando County",
    countyHref: "/counties/hernando",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Brooksville Italian Restaurant & Pizzeria + 2COP",
    businessType: "Italian restaurant and pizzeria",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$599,000",
    packagePriceNumber: 599_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-018",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Duval County",
    countyHref: "/counties/duval",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Jacksonville Turnkey Restaurant + 2COP Beer & Wine",
    businessType: "Turnkey restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Asset Sale",
    packagePrice: "$79,000",
    packagePriceNumber: 79_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-019",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Miami-Dade County",
    countyHref: "/counties/miami-dade",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Miami Restaurant + Speakeasy + 2COP Beer & Wine",
    businessType: "Restaurant with speakeasy",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Asset Sale",
    packagePrice: "$280,000",
    packagePriceNumber: 280_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-020",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Charlotte County",
    countyHref: "/counties/charlotte",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Port Charlotte Sports Pub & Pizza + 2COP Beer & Wine",
    businessType: "Sports pub and pizza restaurant",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$399,000",
    packagePriceNumber: 399_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-Q-021",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Okaloosa County",
    countyHref: "/counties/okaloosa",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Fort Walton Beach Pub-Style Restaurant + 4COP Quota License",
    businessType: "Pub-style restaurant and bar",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$595,000",
    packagePriceNumber: 595_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-022",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Pasco County",
    countyHref: "/counties/pasco",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Holiday Pub + Adult Nightclub + 4COP Quota License",
    businessType: "Pub and adult entertainment nightclub",
    businessCategory: "Gentlemen's Club",
    summaryBusinessType: "Gentlemen's Club",
    transactionType: "Business Asset Sale",
    packagePrice: "$750,000",
    packagePriceNumber: 750_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-SFS-020",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "St. Johns County",
    countyHref: "/counties/st-johns",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "St. Johns County Beach Restaurant + 4COP SFS/SRX",
    businessType: "Oceanside restaurant and bar",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$1,495,000",
    packagePriceNumber: 1_495_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-021",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Polk County",
    countyHref: "/counties/polk",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Polk County Family Sports Bar + 4COP SRX",
    businessType: "Family sports bar and restaurant",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$850,000",
    packagePriceNumber: 850_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-022",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "St. Johns County",
    countyHref: "/counties/st-johns",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "St. Johns County Sports Bar & Restaurant + SRX",
    businessType: "Long-established sports bar and restaurant",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$399,999",
    packagePriceNumber: 399_999,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-023",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Pinellas County",
    countyHref: "/counties/pinellas",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Pinellas County Waterfront Sports Bar + 4COP SRX",
    businessType: "Sports bar and restaurant with docks",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$1,195,000",
    packagePriceNumber: 1_195_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-024",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Pinellas County",
    countyHref: "/counties/pinellas",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Pinellas County Neighborhood Bar & Grill + SRX",
    businessType: "Neighborhood bar and grill",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$190,000",
    packagePriceNumber: 190_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-2COP-021",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Hillsborough County",
    countyHref: "/counties/hillsborough",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Hillsborough County Hookah Lounge + 2COP",
    businessType: "Hookah lounge",
    businessCategory: "Cocktail Lounge",
    summaryBusinessType: "Cocktail Lounge",
    transactionType: "Business Sale",
    packagePrice: "$79,000",
    packagePriceNumber: 79_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-022",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Hillsborough County",
    countyHref: "/counties/hillsborough",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Hillsborough County Sports Bar-Lounge + 2COP",
    businessType: "Sports bar and lounge",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$179,000",
    packagePriceNumber: 179_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-023",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Hillsborough County",
    countyHref: "/counties/hillsborough",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Hillsborough County Jamaican Restaurant + 2COP",
    businessType: "Jamaican restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$256,500",
    packagePriceNumber: 256_500,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-Q-023",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Miami-Dade County",
    countyHref: "/counties/miami-dade",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Brickell Nightclub & Bar + Convertible 4COP License",
    businessType: "Nightclub and bar",
    businessCategory: "Nightclub",
    summaryBusinessType: "Nightclub",
    transactionType: "Business Sale",
    packagePrice: "$800,000",
    packagePriceNumber: 800_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-024",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Pompano Beach Gentlemen's Cabaret + 4COP License",
    businessType: "Nightlife entertainment venue",
    businessCategory: "Gentlemen's Club",
    summaryBusinessType: "Gentlemen's Club",
    transactionType: "Asset Sale",
    packagePrice: "$700,000",
    packagePriceNumber: 700_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-025",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Escambia County",
    countyHref: "/counties/escambia",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Pensacola Saloon & Live Entertainment Venue + 4COP License",
    businessType: "Saloon and live entertainment venue",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business + Real Estate Sale",
    packagePrice: "$1,550,000",
    packagePriceNumber: 1_550_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-026",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Volusia County",
    countyHref: "/counties/volusia",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Ormond Beach Sports Bar + Full 4COP License",
    businessType: "Beachside sports bar",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$650,000",
    packagePriceNumber: 650_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-SFS-025",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Pinellas County",
    countyHref: "/counties/pinellas",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Pinellas Beach Bar & Restaurant + 4COP SRX",
    businessType: "Long-established beach restaurant and bar",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$595,000",
    packagePriceNumber: 595_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-026",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Hillsborough County",
    countyHref: "/counties/hillsborough",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Tampa Restaurant & Bar + 4COP SFS/SRX",
    businessType: "Full-service restaurant and bar",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$779,000",
    packagePriceNumber: 779_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-027",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Pinellas County",
    countyHref: "/counties/pinellas",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Pinellas High-Volume Pizza Bar + 4COP SRX",
    businessType: "Pizza restaurant and bar",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$1,495,000",
    packagePriceNumber: 1_495_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-028",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Hollywood Restaurant, Bar & Entertainment Venue + 4COP SFS",
    businessType: "Restaurant, bar and entertainment venue",
    businessCategory: "Other Hospitality",
    summaryBusinessType: "Entertainment Venue",
    transactionType: "Business Sale",
    packagePrice: "$250,000",
    packagePriceNumber: 250_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-Q-027",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Palm Beach County",
    countyHref: "/counties/palm-beach",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Palm Beach County Italian Restaurant + Dual 4COP License",
    businessType: "Established Italian restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$1,299,000",
    packagePriceNumber: 1_299_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-028",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Palm Beach County",
    countyHref: "/counties/palm-beach",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "West Palm Beach Mediterranean Restaurant + Transferable 4COP",
    businessType: "Established Mediterranean restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Asset Sale",
    packagePrice: "$199,000",
    packagePriceNumber: 199_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-029",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Miami-Dade County",
    countyHref: "/counties/miami-dade",
    licenseType: "3PS Quota / Package Store",
    licenseClass: "quota",
    title: "North Miami Liquor Store + 3PS Quota License",
    businessType: "Liquor store with real estate component",
    businessCategory: "Liquor Store",
    summaryBusinessType: "Liquor Store",
    transactionType: "Business Sale",
    packagePrice: "$3,200,000",
    packagePriceNumber: 3_200_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-031",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Davie Sports Bar & Grille + Broward 4COP Quota License",
    businessType: "Sports bar and grille",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$1,000,000",
    packagePriceNumber: 1_000_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-032",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Duval County",
    countyHref: "/counties/duval",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Jacksonville High-Volume Sports Bar & Grill + 4COP",
    businessType: "High-volume sports bar and grill",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$425,000",
    packagePriceNumber: 425_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-SFS-029",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Palm Beach County",
    countyHref: "/counties/palm-beach",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "North Palm Beach Sports Bar & Grill + 4COP SFS",
    businessType: "Freestanding sports bar and grill",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Asset Sale",
    packagePrice: "$395,000",
    packagePriceNumber: 395_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-030",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Seminole County",
    countyHref: "/counties/seminole",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Seminole County Peruvian Restaurant + 4COP SRX",
    businessType: "Franchised Peruvian restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$350,000",
    packagePriceNumber: 350_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-031",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Hillsborough County",
    countyHref: "/counties/hillsborough",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Hillsborough County Steakhouse + 4COP SRX",
    businessType: "Long-established steakhouse",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$249,000",
    packagePriceNumber: 249_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-032",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Pinellas County",
    countyHref: "/counties/pinellas",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Pinellas Gulf Beach Restaurant + Real Estate + 4COP SRX",
    businessType: "Gulf beach restaurant with real estate",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business + Real Estate Sale",
    packagePrice: "$1,945,000",
    packagePriceNumber: 1_945_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-033",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Hollywood Restaurant, Bar & Entertainment Venue + 4COP SFS",
    businessType: "Restaurant, bar and entertainment venue",
    businessCategory: "Other Hospitality",
    summaryBusinessType: "Entertainment Venue",
    transactionType: "Business Sale",
    packagePrice: "$150,000",
    packagePriceNumber: 150_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-034",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Orange County",
    countyHref: "/counties/orange",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Windermere Italian Restaurant + 4COP SRX",
    businessType: "Upscale Italian restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$3,500,000",
    packagePriceNumber: 3_500_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-035",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Palm Beach County",
    countyHref: "/counties/palm-beach",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Delray Beach Atlantic Avenue Restaurant + 4COP SFS",
    businessType: "Mediterranean full-service restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$615,000",
    packagePriceNumber: 615_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-2COP-024",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Hollywood Turnkey Restaurant + 2COP Beer & Wine",
    businessType: "Gourmet burger restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Asset Sale",
    packagePrice: "$125,000",
    packagePriceNumber: 125_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-025",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Polk County",
    countyHref: "/counties/polk",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Auburndale Turn-Key Bar + 2COP Beer & Wine",
    businessType: "Neighborhood bar",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$100,000",
    packagePriceNumber: 100_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-026",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Duval County",
    countyHref: "/counties/duval",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Jacksonville Sushi Restaurant + 2COP Beer & Wine",
    businessType: "Established sushi restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$160,000",
    packagePriceNumber: 160_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-027",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Hillsborough County",
    countyHref: "/counties/hillsborough",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Tampa Breakfast Restaurant + 2COP Beer & Wine",
    businessType: "Breakfast restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$260,000",
    packagePriceNumber: 260_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-Q-033",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Seminole County",
    countyHref: "/counties/seminole",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Sanford Mexican Restaurant & Lounge + 4COP License",
    businessType: "Mexican restaurant and lounge",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$350,000",
    packagePriceNumber: 350_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-034",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Hollywood Italian Restaurant + 4COP License",
    businessType: "Italian restaurant and pizzeria",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$449,999",
    packagePriceNumber: 449_999,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-035",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Oakland Park Restaurant & Lounge + Real Estate + 4COP",
    businessType: "Restaurant, lounge and bar with real estate",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business + Real Estate Sale",
    packagePrice: "$1,975,000",
    packagePriceNumber: 1_975_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-SFS-036",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Orange County",
    countyHref: "/counties/orange",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Downtown Orlando Restaurant & Bar + 4COP SFS",
    businessType: "Restaurant and bar",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$750,000",
    packagePriceNumber: 750_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-2COP-028",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Seminole County",
    countyHref: "/counties/seminole",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Sanford Turnkey Restaurant + 2COP Beer & Wine",
    businessType: "Turnkey restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Asset Sale",
    packagePrice: "$99,999",
    packagePriceNumber: 99_999,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-029",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "NW Broward Restaurant + 2COP Beer & Wine",
    businessType: "Upscale restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$850,000",
    packagePriceNumber: 850_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
];

export const businessQuotaListings = businessQuotaListingRecords.filter(
  (listing) => listing.publicationStatus === "published" && listing.licenseClass === "quota",
);

export const businessSfsListings = businessQuotaListingRecords.filter(
  (listing) => listing.publicationStatus === "published" && listing.licenseClass === "sfs",
);

export const business2copListings = businessQuotaListingRecords.filter(
  (listing) => listing.publicationStatus === "published" && listing.licenseClass === "2cop",
);

const businessQuotaReferences = new Set(
  businessQuotaListingRecords.flatMap((listing) =>
    [listing.listingReference, ...(listing.inventoryReferences ?? [])].map((reference) =>
      reference.toUpperCase(),
    ),
  ),
);

export function isBusinessQuotaListing(
  listing: Pick<ListingWithInventoryClass, "sourceRef">,
) {
  return businessQuotaReferences.has(listing.sourceRef?.trim().toUpperCase() ?? "");
}

export function standaloneQuotaListings<T extends Pick<ListingWithInventoryClass, "sourceRef">>(
  listings: T[],
) {
  return listings.filter((listing) => !isBusinessQuotaListing(listing));
}

export function businessQuotaListingsForCounty(county: string) {
  return businessQuotaListings.filter((listing) => listing.county === county);
}
