import type { ListingWithInventoryClass } from "@/lib/listing-inventory-class";

export type QuotaOfferClassification =
  | "standalone_quota"
  | "business_package"
  | "dual_offering"
  | "excluded";

export type QuotaOfferFacts = {
  isTransferableQuotaLicense: boolean;
  includesOperatingBusiness: boolean;
  licenseAvailableSeparately: boolean;
};

export const FLLM_QUOTA_LISTING_OPERATING_RULES = [
  {
    classification: "standalone_quota",
    label: "Standalone Quota License",
    placement: "Standalone license inventory",
    description:
      "A separately purchasable 4COP or 3PS quota license belongs only in FLLM's standalone inventory and market statistics.",
  },
  {
    classification: "business_package",
    label: "Business + Quota License",
    placement: "Business-package inventory",
    description:
      "An operating business sold with an included quota license belongs only in Businesses With Quota Licenses and is excluded from standalone statistics.",
  },
  {
    classification: "dual_offering",
    label: "Separately Authorized Offers",
    placement: "Two distinct listings",
    description:
      "When a broker expressly offers the business package and the license separately, FLLM creates distinct records, prices, disclosures, and search intent for each offer.",
  },
  {
    classification: "excluded",
    label: "Nonquota or Premises-Dependent License",
    placement: "Excluded from quota inventory",
    description:
      "A business involving only a nonquota, specialty, or premises-dependent license is not published as FLLM quota-license inventory.",
  },
] as const satisfies ReadonlyArray<{
  classification: QuotaOfferClassification;
  label: string;
  placement: string;
  description: string;
}>;

export function classifyQuotaOffer({
  isTransferableQuotaLicense,
  includesOperatingBusiness,
  licenseAvailableSeparately,
}: QuotaOfferFacts): QuotaOfferClassification {
  if (!isTransferableQuotaLicense) return "excluded";
  if (includesOperatingBusiness && licenseAvailableSeparately) return "dual_offering";
  if (includesOperatingBusiness) return "business_package";
  return "standalone_quota";
}

export type BusinessQuotaCategory =
  | "Bar"
  | "Cocktail Lounge"
  | "Nightclub"
  | "Restaurant"
  | "Bowling Alley"
  | "Liquor Store"
  | "Marina"
  | "Gentlemen's Club"
  | "Hotel / Motel"
  | "Country Club"
  | "Other Hospitality";

export type BusinessQuotaListing = {
  listingReference: string;
  inventoryReferences?: readonly string[];
  href: string;
  county: string;
  countyHref: string;
  licenseType: "4COP Quota" | "3PS Quota / Package Store" | "4COP SFS/SRX" | "2COP Beer & Wine";
  licenseClass: "quota" | "sfs" | "2cop";
  title: string;
  businessType: string;
  businessCategory: BusinessQuotaCategory;
  summaryBusinessType: string;
  transactionType: string;
  packagePrice: string;
  packagePriceNumber: number;
  allocatedLicenseValue: string;
  brokerName: string;
  brokerage: string;
  featured: boolean;
  listingTier?: "featured" | "market";
  marketViewHref?: string;
  publicationStatus: "published" | "preview";
  classification: "business_package" | "business_sfs" | "business_2cop";
  sellerDirect?: boolean;
};

/**
 * Canonical registry for third-party broker offerings that include an
 * operating business and a quota license. These records are deliberately
 * separate from statewide standalone-license inventory, pricing statistics,
 * county counts, market comparisons, and the Exchange.
 *
 * Preview records remain classified here so they cannot leak into standalone
 * inventory, but they are not exposed on the public business inventory until
 * the broker listing is approved and publicationStatus becomes "published".
 */
export const businessQuotaListingRecords: BusinessQuotaListing[] = [
  {
    listingReference: "FLLM-ANTEZZA",
    href: "/listings/fllm-antezza",
    county: "Pinellas County",
    countyHref: "/counties/pinellas",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Pinellas County Cocktail Lounge + 4COP Quota License",
    businessType: "Upscale cocktail lounge",
    businessCategory: "Cocktail Lounge",
    summaryBusinessType: "Cocktail Lounge",
    transactionType: "Asset Sale",
    packagePrice: "$999,000",
    packagePriceNumber: 999_000,
    allocatedLicenseValue: "$460,000",
    brokerName: "Alessandro Antezza",
    brokerage: "SUNSHINEAGLE LLC",
    featured: true,
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-DESAMOURS",
    href: "/listings/fllm-desamours",
    county: "Martin County",
    countyHref: "/counties/martin",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Iconic Jensen Beach Bar + 4COP Quota License",
    businessType: "Long-established neighborhood bar",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Asset Sale",
    packagePrice: "$650,000",
    packagePriceNumber: 650_000,
    allocatedLicenseValue: "$600,000 est.",
    brokerName: "JR DesAmours",
    brokerage: "Business Exit Advisors",
    featured: true,
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-NEGOVAN",
    href: "/listings/fllm-negovan",
    county: "Miami-Dade County",
    countyHref: "/counties/miami-dade",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Miami Adult Nightclub + 4COP Quota License",
    businessType: "Premium adult-entertainment business",
    businessCategory: "Gentlemen's Club",
    summaryBusinessType: "Gentlemen's Club",
    transactionType: "Business Package",
    packagePrice: "$3,500,000",
    packagePriceNumber: 3_500_000,
    allocatedLicenseValue: "$250,000",
    brokerName: "Julie Negovan",
    brokerage: "Patricia Burnside Realty",
    featured: true,
    publicationStatus: "preview",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MELLO",
    inventoryReferences: ["FLLM-265072"],
    href: "/listings/fllm-mello",
    county: "Palm Beach County",
    countyHref: "/counties/palm-beach",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Delray Beach Restaurant + 4COP Quota License",
    businessType: "Turnkey full-service restaurant and bar",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Asset Sale",
    packagePrice: "$359,000",
    packagePriceNumber: 359_000,
    allocatedLicenseValue: "$200,000",
    brokerName: "Leonard Mello",
    brokerage: "We Sell Restaurants",
    featured: true,
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-ZOBERG",
    href: "/listings/fllm-zoberg",
    county: "Miami-Dade County",
    countyHref: "/counties/miami-dade",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Miami-Dade Mexican Restaurant + 4COP SFS / SRX License",
    businessType: "Mexican-Latin restaurant and entertainment venue",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$1,200,000",
    packagePriceNumber: 1_200_000,
    allocatedLicenseValue: "Location-specific",
    brokerName: "Brian Zoberg",
    brokerage: "Suncoast Business Consultants",
    featured: true,
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-KOPP",
    href: "/listings/fllm-kopp",
    county: "Miami-Dade County",
    countyHref: "/counties/miami-dade",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Miami Peruvian Restaurant + 2COP Beer & Wine License",
    businessType: "Peruvian-Mediterranean restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$599,999",
    packagePriceNumber: 599_999,
    allocatedLicenseValue: "No separate quota value",
    brokerName: "Marianella Kopp",
    brokerage: "Seller Direct",
    sellerDirect: true,
    featured: true,
    publicationStatus: "preview",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-Q-001",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Martin County",
    countyHref: "/counties/martin",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Martin County Pub + 4COP Quota License",
    businessType: "Pub and bar",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$795,000",
    packagePriceNumber: 795_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-002",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Sarasota County",
    countyHref: "/counties/sarasota",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Sarasota County Bar + 4COP Quota License",
    businessType: "Bar and lounge",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$756,000",
    packagePriceNumber: 756_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-003",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "St. Lucie County",
    countyHref: "/counties/st-lucie",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "St. Lucie County Bar + 4COP Quota License",
    businessType: "Bar",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$420,000",
    packagePriceNumber: 420_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-004",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "St. Johns County",
    countyHref: "/counties/st-johns",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "St. Augustine Bar / Restaurant + 4COP Quota License",
    businessType: "Sports bar and restaurant",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$999,000",
    packagePriceNumber: 999_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-SFS-001",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Broward County Full-Service Restaurant + 4COP SFS/SRX",
    businessType: "Full-service restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Asset Sale",
    packagePrice: "$499,000",
    packagePriceNumber: 499_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-002",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Fort Lauderdale Italian Restaurant + 4COP SFS",
    businessType: "Italian restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$400,000",
    packagePriceNumber: 400_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-003",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Orange County",
    countyHref: "/counties/orange",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Orlando Restaurant + 4COP SFS",
    businessType: "Full-service restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$250,000",
    packagePriceNumber: 250_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-004",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Seminole County",
    countyHref: "/counties/seminole",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Seminole County Restaurant + 4COP SFS",
    businessType: "Full-service restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$150,000",
    packagePriceNumber: 150_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-2COP-001",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Orange County",
    countyHref: "/counties/orange",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Orlando Restaurant + 2COP Beer & Wine",
    businessType: "Franchise restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$275,000",
    packagePriceNumber: 275_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-002",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Manatee County",
    countyHref: "/counties/manatee",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Lakewood Ranch Restaurant + 2COP Beer & Wine",
    businessType: "Restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$135,000",
    packagePriceNumber: 135_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-003",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Hillsborough County",
    countyHref: "/counties/hillsborough",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Hillsborough County Restaurant + 2COP Beer & Wine",
    businessType: "Breakfast and lunch restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$199,999",
    packagePriceNumber: 199_999,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-004",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Brevard County",
    countyHref: "/counties/brevard",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Brevard County Restaurant + 2COP Beer & Wine",
    businessType: "Italian restaurant and wine bar",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$315,000",
    packagePriceNumber: 315_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-005",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Miami-Dade County",
    countyHref: "/counties/miami-dade",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Downtown Miami Restaurant + 2COP Beer & Wine",
    businessType: "Turnkey restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$195,000",
    packagePriceNumber: 195_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },

  {
    listingReference: "FLLM-MKT-Q-005",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Duval County",
    countyHref: "/counties/duval",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Jacksonville Bar + 4COP Quota License",
    businessType: "High-capacity bar and restaurant",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$950,000",
    packagePriceNumber: 950_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-006",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Duval County",
    countyHref: "/counties/duval",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Atlantic Beach Bar + Real Estate + 4COP Quota License",
    businessType: "Neighborhood bar with real estate",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business + Real Estate Sale",
    packagePrice: "$2,650,000",
    packagePriceNumber: 2_650_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-007",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Hillsborough County",
    countyHref: "/counties/hillsborough",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Tampa Bay Sports Bar + 4COP Quota License",
    businessType: "Sports bar and grill",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$549,900",
    packagePriceNumber: 549_900,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-008",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "3PS Quota / Package Store",
    licenseClass: "quota",
    title: "Broward County Liquor Store + 3PS Quota License",
    businessType: "Retail liquor store",
    businessCategory: "Liquor Store",
    summaryBusinessType: "Liquor Store",
    transactionType: "Business Sale",
    packagePrice: "$435,000",
    packagePriceNumber: 435_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-Q-009",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Miami-Dade County",
    countyHref: "/counties/miami-dade",
    licenseType: "3PS Quota / Package Store",
    licenseClass: "quota",
    title: "Miami Liquor Store + 3PS Quota License",
    businessType: "Established retail liquor store",
    businessCategory: "Liquor Store",
    summaryBusinessType: "Liquor Store",
    transactionType: "Business Sale",
    packagePrice: "$420,000",
    packagePriceNumber: 420_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-SFS-005",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Brevard County",
    countyHref: "/counties/brevard",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Brevard County Restaurant + 4COP SFS/SRX License",
    businessType: "Restaurant and bar",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Asset Sale",
    packagePrice: "$799,000",
    packagePriceNumber: 799_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-006",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Oakland Park Restaurant + Bar + 4COP SFS/SRX",
    businessType: "Restaurant and bar",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Asset Sale",
    packagePrice: "$450,000",
    packagePriceNumber: 450_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-007",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Pinellas County",
    countyHref: "/counties/pinellas",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Clearwater Sports Bar + 4COP SFS/SRX License",
    businessType: "High-volume sports bar and restaurant",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$950,000",
    packagePriceNumber: 950_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-008",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Sarasota County",
    countyHref: "/counties/sarasota",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Downtown Sarasota Restaurant + 4COP SFS/SRX",
    businessType: "Restaurant and full bar",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Asset Sale",
    packagePrice: "$215,000",
    packagePriceNumber: 215_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-009",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Miramar Entertainment Venue + Restaurant + 4COP SFS/SRX",
    businessType: "Restaurant and entertainment venue",
    businessCategory: "Other Hospitality",
    summaryBusinessType: "Entertainment Venue",
    transactionType: "Business Sale",
    packagePrice: "$75,000",
    packagePriceNumber: 75_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-2COP-006",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Palm Beach County",
    countyHref: "/counties/palm-beach",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Palm Beach County Breakfast & Lunch Restaurant + 2COP",
    businessType: "Breakfast and lunch restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$220,000",
    packagePriceNumber: 220_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-007",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Osceola County",
    countyHref: "/counties/osceola",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "St. Cloud Restaurant + Bar + 2COP Beer & Wine",
    businessType: "Restaurant and bar",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$159,999",
    packagePriceNumber: 159_999,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-008",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Miami-Dade County",
    countyHref: "/counties/miami-dade",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Miami-Dade Cafe & Bakery + 2COP Beer & Wine",
    businessType: "Cafe, bakery and restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$599,000",
    packagePriceNumber: 599_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-Q-010",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Pinellas County",
    countyHref: "/counties/pinellas",
    licenseType: "4COP Quota",
    licenseClass: "quota",
    title: "Downtown Pinellas County Bar + 4COP Quota License",
    businessType: "Downtown bar",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$1,050,000",
    packagePriceNumber: 1_050_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_package",
  },
  {
    listingReference: "FLLM-MKT-SFS-010",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Fort Lauderdale Beach Restaurant + 4COP SFS/SRX",
    businessType: "Beachfront full-service restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$350,000",
    packagePriceNumber: 350_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-011",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Pasco County",
    countyHref: "/counties/pasco",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Pasco County Italian Restaurant + 4COP SFS/SRX",
    businessType: "Italian restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$519,000",
    packagePriceNumber: 519_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-012",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Pompano Beach Restaurant + 4COP SFS/SRX",
    businessType: "Full-service restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$249,000",
    packagePriceNumber: 249_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-013",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "East Fort Lauderdale Italian Restaurant + 4COP SFS/SRX",
    businessType: "Italian restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$400,000",
    packagePriceNumber: 400_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-014",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Palm Beach County",
    countyHref: "/counties/palm-beach",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Lake Worth Tavern + 4COP SFS/SRX",
    businessType: "Neighborhood tavern and grill",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$199,000",
    packagePriceNumber: 199_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-SFS-015",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Sarasota County",
    countyHref: "/counties/sarasota",
    licenseType: "4COP SFS/SRX",
    licenseClass: "sfs",
    title: "Sarasota Restaurant + Real Estate + 4COP SFS/SRX",
    businessType: "Established restaurant with real estate",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business + Real Estate Sale",
    packagePrice: "$1,549,000",
    packagePriceNumber: 1_549_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_sfs",
  },
  {
    listingReference: "FLLM-MKT-2COP-009",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Sarasota County",
    countyHref: "/counties/sarasota",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Sarasota Pub + 2COP Beer & Wine",
    businessType: "Long-established pub and restaurant",
    businessCategory: "Bar",
    summaryBusinessType: "Bar",
    transactionType: "Business Sale",
    packagePrice: "$475,000",
    packagePriceNumber: 475_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-010",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Charlotte County",
    countyHref: "/counties/charlotte",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Punta Gorda Sushi Restaurant + 2COP Beer & Wine",
    businessType: "Sushi restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Asset Sale",
    packagePrice: "$110,000",
    packagePriceNumber: 110_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-011",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Manatee County",
    countyHref: "/counties/manatee",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Manatee County Wine Store & Wine Bar + 2COP",
    businessType: "Retail wine store and wine bar",
    businessCategory: "Liquor Store",
    summaryBusinessType: "Wine Store & Bar",
    transactionType: "Business Sale",
    packagePrice: "$399,999",
    packagePriceNumber: 399_999,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-012",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Broward County",
    countyHref: "/counties/broward",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Broward County Cuban Restaurant + 2COP Beer & Wine",
    businessType: "Cuban restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$99,000",
    packagePriceNumber: 99_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-013",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "St. Lucie County",
    countyHref: "/counties/st-lucie",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "St. Lucie County Breakfast & Lunch Cafe + 2COP",
    businessType: "Breakfast and lunch cafe",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$375,000",
    packagePriceNumber: 375_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-014",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Palm Beach County",
    countyHref: "/counties/palm-beach",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Boynton Beach BBQ Restaurant + 2COP Beer & Wine",
    businessType: "BBQ restaurant",
    businessCategory: "Restaurant",
    summaryBusinessType: "Restaurant",
    transactionType: "Business Sale",
    packagePrice: "$99,000",
    packagePriceNumber: 99_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
  {
    listingReference: "FLLM-MKT-2COP-015",
    href: "/market-data/heat-map",
    marketViewHref: "/market-data/heat-map",
    county: "Pinellas County",
    countyHref: "/counties/pinellas",
    licenseType: "2COP Beer & Wine",
    licenseClass: "2cop",
    title: "Pinellas County Dog Bar & Social Venue + 2COP",
    businessType: "Dog-friendly bar and entertainment venue",
    businessCategory: "Other Hospitality",
    summaryBusinessType: "Entertainment Venue",
    transactionType: "Asset Sale",
    packagePrice: "$275,000",
    packagePriceNumber: 275_000,
    allocatedLicenseValue: "",
    brokerName: "",
    brokerage: "",
    featured: false,
    listingTier: "market",
    publicationStatus: "published",
    classification: "business_2cop",
  },
];

export const businessQuotaListings = businessQuotaListingRecords.filter(
  (listing) => listing.publicationStatus === "published" && listing.licenseClass === "quota",
);

export const businessSfsListings = businessQuotaListingRecords.filter(
  (listing) => listing.publicationStatus === "published" && listing.licenseClass === "sfs",
);

export const business2copListings = businessQuotaListingRecords.filter(
  (listing) => listing.publicationStatus === "published" && listing.licenseClass === "2cop",
);

const businessQuotaReferences = new Set(
  businessQuotaListingRecords.flatMap((listing) =>
    [listing.listingReference, ...(listing.inventoryReferences ?? [])].map((reference) =>
      reference.toUpperCase(),
    ),
  ),
);

export function isBusinessQuotaListing(
  listing: Pick<ListingWithInventoryClass, "sourceRef">,
) {
  return businessQuotaReferences.has(listing.sourceRef?.trim().toUpperCase() ?? "");
}

export function standaloneQuotaListings<T extends Pick<ListingWithInventoryClass, "sourceRef">>(
  listings: T[],
) {
  return listings.filter((listing) => !isBusinessQuotaListing(listing));
}

export function businessQuotaListingsForCounty(county: string) {
  return businessQuotaListings.filter((listing) => listing.county === county);
}
