const countyDescriptions: Record<string, string> = {
  "Alachua County": "Alachua County is anchored by Gainesville and the University of Florida, with a diverse economy supported by education, healthcare, research, and hospitality.",
  "Bay County": "Bay County in the Panhandle is home to Panama City and Panama City Beach, with a strong tourism, dining, and hospitality market.",
  "Brevard County": "Brevard County on Florida's Space Coast is home to Kennedy Space Center, aerospace employers, growing communities, and Atlantic beaches.",
  "Broward County": "Broward County anchors South Florida around Fort Lauderdale, known for its beaches, boating canals, dense population, dining, and nightlife.",
  "Charlotte County": "Charlotte County on the southwest Gulf Coast is home to Punta Gorda, with a growing population and strong boating, fishing, and hospitality activity.",
  "Citrus County": "Citrus County on Florida's Nature Coast is known for Crystal River, natural springs, waterfront recreation, and growing residential communities.",
  "Clay County": "Clay County lies southwest of Jacksonville and includes fast-growing suburban communities supported by military, retail, dining, and residential development.",
  "Collier County": "Collier County in Southwest Florida is home to Naples, known for affluent communities, golf, luxury tourism, dining, and access to the Everglades.",
  "DeSoto County": "DeSoto County is a rural south-central Florida market centered on Arcadia, with agriculture, cattle ranching, local commerce, and regional travel activity.",
  "Duval County": "Duval County is anchored by Jacksonville, a major port, finance, logistics, healthcare, sports, dining, and entertainment market.",
  "Escambia County": "Escambia County is the westernmost Panhandle county and home to Pensacola, with military, tourism, education, dining, and Gulf Coast activity.",
  "Hernando County": "Hernando County is a growing Nature Coast market north of Tampa, known for suburban development, springs, recreation, and expanding retail and dining demand.",
  "Hillsborough County": "Hillsborough County is anchored by Tampa, one of Florida's largest business, tourism, healthcare, sports, dining, and entertainment markets.",
  "Indian River County": "Indian River County on the Treasure Coast is centered on Vero Beach, with affluent coastal communities, tourism, boating, retail, and hospitality activity.",
  "Lake County": "Lake County in Central Florida, northwest of Orlando, is known for its chain of lakes, fast-growing communities, tourism, recreation, and suburban development.",
  "Lee County": "Lee County in Southwest Florida includes Fort Myers and Cape Coral, with rapid population growth, beaches, boating, tourism, and a large hospitality market.",
  "Leon County": "Leon County is home to Tallahassee, the state capital, with an economy supported by government, universities, healthcare, dining, and regional commerce.",
  "Manatee County": "Manatee County on Florida's Gulf Coast is home to Bradenton, with beaches, boating, tourism, residential growth, and expanding dining demand.",
  "Marion County": "Marion County is anchored by Ocala, known for horse farms, logistics, healthcare, residential growth, tourism, and regional commerce.",
  "Martin County": "Martin County on the Treasure Coast is known for boating, affluent coastal communities, protected shorelines, tourism, and a strong local dining market.",
  "Miami-Dade County": "Miami-Dade County is Florida's most populous county and a major international center for tourism, finance, trade, culture, dining, and nightlife.",
  "Monroe County": "Monroe County encompasses the Florida Keys, one of the state's strongest tourism, boating, fishing, dining, and hospitality markets.",
  "Okaloosa County": "Okaloosa County includes Destin and Fort Walton Beach, with major military installations, Gulf tourism, boating, dining, and hospitality activity.",
  "Orange County": "Orange County is anchored by Orlando, one of the world's leading tourism destinations and a major market for hotels, restaurants, entertainment, and conventions.",
  "Osceola County": "Osceola County is a fast-growing Central Florida market south of Orlando, anchored by Kissimmee and the region's tourism and hospitality corridor.",
  "Palm Beach County": "Palm Beach County stretches along Florida's southeast coast and features affluent communities, tourism, boating, dining, retail, and year-round population growth.",
  "Pasco County": "Pasco County is a rapidly growing Tampa Bay market with expanding suburban communities, retail centers, recreation, restaurants, and hospitality demand.",
  "Pinellas County": "Pinellas County includes St. Petersburg and Clearwater, with dense coastal communities, Gulf beaches, tourism, arts, dining, and nightlife.",
  "Polk County": "Polk County sits between Tampa and Orlando and is anchored by Lakeland, with logistics, manufacturing, tourism, residential growth, and regional commerce.",
  "Santa Rosa County": "Santa Rosa County includes Gulf Breeze, Navarre, and growing communities near Pensacola, supported by military, tourism, beaches, and residential development.",
  "Sarasota County": "Sarasota County is a Gulf Coast destination known for white-sand beaches, arts, culture, affluent communities, tourism, and a strong dining market.",
  "Seminole County": "Seminole County is a prosperous suburban market north of Orlando, known for strong schools, lakeside communities, retail, dining, and population growth.",
  "St. Johns County": "St. Johns County is home to historic St. Augustine and fast-growing coastal communities, with strong tourism, hospitality, schools, and residential development.",
  "St. Lucie County": "St. Lucie County on the Treasure Coast is home to Port St. Lucie, with rapid residential growth, coastal recreation, healthcare, retail, and hospitality activity.",
  "Volusia County": "Volusia County is home to Daytona Beach, with motorsports, Atlantic beaches, tourism, universities, dining, and growing residential communities.",
};

export function countyListingDescription(county: string) {
  return countyDescriptions[county] ?? `${county || "This Florida county"} offers a mix of local commerce, residential communities, tourism, dining, and hospitality activity within Florida.`;
}
