import type { Metadata } from "next";
import Link from "next/link";
import SpanishPageShell from "@/components/es/SpanishPageShell";

const url = "https://www.floridaliquorlicensemarket.com/es/tipos-de-licencias";
export const metadata: Metadata = { title: "Tipos de licencias de bebidas alcohólicas de Florida", description: "Explicación en español de las licencias 4COP Quota, 3PS Quota, 2COP y 4COP-SFS/SRX de Florida.", alternates: { canonical: url, languages: { "es": url, "en-US": "https://www.floridaliquorlicensemarket.com/resources/florida-liquor-license-types" } } };

export default function SpanishTypesPage() {
  return <SpanishPageShell eyebrow="Tipos de licencia" title="Comprenda las principales series de licencias de Florida" intro="Los códigos oficiales no se traducen. La siguiente información resume sus usos generales; la aprobación final depende de la autoridad reguladora, la ubicación y la operación propuesta.">
    <div className="es-card-grid"><article className="es-card"><h2>4COP Quota</h2><p>Licencia de cuota para cerveza, vino y bebidas destiladas, comúnmente utilizada por bares, restaurantes, hoteles y clubes, sujeta a las aprobaciones aplicables.</p><Link href="/license-types/4cop-quota">Detalles oficiales →</Link></article><article className="es-card"><h2>3PS Quota</h2><p>Serie de cuota utilizada principalmente para ventas de bebidas alcohólicas selladas fuera del establecimiento, como una licorería.</p><Link href="/license-types/3ps-package-store">Detalles oficiales →</Link></article><article className="es-card"><h2>2COP</h2><p>Permite ventas de cerveza y vino según las condiciones de la licencia. No incluye bebidas destiladas.</p><Link href="/license-types/2cop-beer-wine">Detalles oficiales →</Link></article><article className="es-card"><h2>4COP-SFS / SRX</h2><p>Licencia especial de restaurante sujeta a requisitos legales de asientos, área, servicio de comidas y porcentaje de ingresos.</p><Link href="/license-types/4cop-sfs-restaurant">Detalles oficiales →</Link></article><article className="es-card"><h2>Conversión de serie</h2><p>Una licencia de cuota puede utilizarse o convertirse entre determinadas series, incluida 3PS y la familia 4COP, pero requiere aprobación regulatoria y de zonificación.</p><Link href="/resources/florida-liquor-license-system">Cómo funciona el sistema →</Link></article><article className="es-card"><h2>Todos los tipos</h2><p>Florida mantiene numerosas clasificaciones para hoteles, restaurantes, clubes, fabricantes, distribuidores y otros usos.</p><Link href="/resources/florida-liquor-license-types">Directorio completo →</Link></article></div>
  </SpanishPageShell>;
}
