create extension if not exists pgcrypto;

create table if not exists public.listing_discovery_runs (
  id uuid primary key default gen_random_uuid(),
  job_name text not null,
  status text not null check (status in ('running', 'succeeded', 'failed')),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  summary jsonb not null default '{}'::jsonb,
  error_text text
);

create index if not exists listing_discovery_runs_started_at_idx
  on public.listing_discovery_runs (started_at desc);

create table if not exists public.listing_discovery_candidates (
  id bigint generated by default as identity primary key,
  source_url text not null unique,
  source_id text not null,
  source_name text not null,
  title text not null,
  reason text not null,
  relevance_score numeric,
  county text,
  license_type text,
  price numeric,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  last_run_id uuid references public.listing_discovery_runs(id) on delete set null,
  review_status text not null default 'pending' check (review_status in ('pending', 'approved', 'rejected')),
  reviewer_notes text
);

create index if not exists listing_discovery_candidates_review_idx
  on public.listing_discovery_candidates (review_status, last_seen_at desc);

alter table public.listing_discovery_runs enable row level security;
alter table public.listing_discovery_candidates enable row level security;
